name: "adikasi"

networks:
  adikasi:
    name: adikasi
    driver: bridge

services:
  adikasi.api:
    image: nginx:stable-alpine
    container_name: adikasi.api
    ports:
      - "8080:80"
    networks:
      - adikasi
    volumes:
      - "./laravel:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - adikasi.mysql
      - adikasi.php

  adikasi.php:
    container_name: adikasi.php
    build:
      context: ./laravel
      dockerfile: Dockerfile
    image: "php:8.2-composer"
    volumes:
      - "./laravel:/var/www/html"
    networks:
      - adikasi

  adikasi.mysql:
    image: mariadb:10.4.32
    container_name: adikasi.mysql
    restart: unless-stopped
    tty: true
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    networks:
      - adikasi
